### ISSUE TITLE
Use gcc package on Linux

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/pykdtree-feedstock#2]
As we need OpenMP here, we should actually use the `gcc` and `libgcc` packages on both Linux and Mac. The reason is we need to have a copy of `libgomp` that we can distribute with the binary.

**Comment by jakirkham** [comment]
It doesn't seem this is actually resolved. This is building on Linux with `libgomp`, but not shipping it. As a result, there are a variety of platforms where this will not work correctly. Could this library either be shipped or OpenMP support disabled via `USE_OMP`?

**Comment by ocefpaf** [comment]
That is solved in the next uncommitted PR.  I am just waiting on the author comment to commit.
