### ISSUE TITLE
Add `openmp` dependency and turn on openmp support

### ISSUE THREAD

**Issue by djhoese** [conda-forge/pykdtree-feedstock#22]
Related to https://github.com/storpipfugl/pykdtree/issues/37

Pykdtree can be built with openmp support, but this recipe currently disables it for OSX and Windows. It seems like pykdtree builds fine with conda's compilers and `intel-openmp` installed from the defaults channel. I see conda-forge has an openmp package too. @ocefpaf or @storpipfugl or anyone else, does this sound like bad idea? Is trying to install `openmp` on all systems possible?

**Comment by ocefpaf** [comment]
>  @ocefpaf or @storpipfugl or anyone else, does this sound like bad idea?

I think it is a good idea :smile: The only reason I did not do this by default in the past was the lack of `openmp` support in our build system for OS X and Windows.

**Comment by cheginit** [comment]
@ocefpaf Can `llvm-openmp` be used to add OpenMP support for `osx`?

**Comment by ocefpaf** [comment]
> [@ocefpaf](https://github.com/ocefpaf) Can `llvm-openmp` be used to add OpenMP support for `osx`?

No idea. Worth a try if you want to send a PR.

**Comment by mraspaud** [comment]
I think this can be closed, right?
